name: CI

on: [push]

strategy:
  matrix:
    os: [macos-latest, windows-latest, ubuntu-latest]
    node: [10, 12, 14]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
        with:
          # The Node.js version to configure
          node-version: ${{ matrix.node }}
    - name: install deps
      run: npm ci

    - name: install global tool
      run: npm i -g @mpxjs/cli

    - name: test
      run: |
        node __test__/testWxCrossWeb.js
        node __test__/testWxCrossNoWeb.js
        node __test__/testWxPlugin.js
        node __test__/testWxNoCross.js
